class GarlicPowder {
static int refInt;
static byte refByte;
static short refShort;
static float refFloat;
static double refDouble;
static long refLong;
static boolean refBoolean;
static String refString;
static char refChar;}